# Generated by Django 3.2.5 on 2023-11-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_balacne_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
