# Generated by Django 3.2.5 on 2023-11-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='balacne',
            new_name='balance',
        ),
    ]
