# Generated by Django 3.2.5 on 2023-11-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20231113_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_asset', models.CharField(default='Stock', max_length=255)),
            ],
        ),
    ]
