# Generated by Django 3.2.5 on 2023-11-15 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.account')),
                ('amount_to_invest', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_investment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            bases=('core.account',),
        ),
        migrations.CreateModel(
            name='InvestmentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_have', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.asset')),
                ('investment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investmentaccount')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('initial_value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('type_transaction', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=255)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.investmentasset')),
                ('investment_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investmentaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveInvestmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_investment_for_user', to='core.investmentaccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_investment_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
