# Generated by Django 3.2.5 on 2023-11-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_activeinvestmentaccount_investmentaccount_investmentasset_investmenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentasset',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentasset',
            name='quantity_have',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
