# Generated by Django 3.2.5 on 2023-11-16 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20231116_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttransaction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investmentasset'),
        ),
    ]
