# Generated by Django 3.2.5 on 2023-11-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20231117_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentasset',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
