# Generated by Django 3.2.5 on 2023-11-20 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_investmentasset_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asset'),
        ),
    ]
